# Generated by Django 3.1.7 on 2021-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Age', models.IntegerField(max_length=3)),
                ('Blood_Group', models.CharField(max_length=5)),
            ],
        ),
    ]
